### ISSUE TITLE
OLED does not work when started using systemd 

### ISSUE THREAD

**Issue by paulsykes** [akgnah/rockpi-sata#1]
When starting from systemd, top_board always = 0 and OLED does not show anything.
Starting manually from terminal, top_board = 1 and OLED outputs as expected.

Fresh install on Raspbian buster lite.

**Comment by paulsykes** [comment]
Installed using script from https://rock.sh/get-rockpi-sata

To fix the problem:-
Add 'WorkingDirectory=/usr/bin/rockpi-sata' to /lib/systemd/systemrockpi-sata.service

Full instructions:-
```sudo systemctl stop rockpi-sata.service```
```sudo nano /lib/systemd/system/rockpi-sata.service```

[Unit]
Description=Rockpi SATA Hat

[Service]
Type=simple
ExecStart=/usr/bin/python3 /usr/bin/rockpi-sata/main.py on
ExecStop=/usr/bin/python3 /usr/bin/rockpi-sata/main.py off
Restart=on-failure
WorkingDirectory=/usr/bin/rockpi-sata

[Install]
WantedBy=multi-user.target

```sudo systemctl daemon-reload```
```sudo systemctl start rockpi-sata.service```

**Comment by akgnah** [comment]
I didn't find this problem in the previous test, I will verify it tomorrow.
I have now added the work path to the rockpi-sata.service. 

Thank you for your help.

**Comment by stephanepapin** [comment]
Hi,
Have same problem, I've checked my **/lib/systemd/system/rockpi-sata.service**
**WorkingDirectory=/usr/bin/rockpi-sata** is already inside
Regards
